//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace holy_water.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("holy_water.Resources.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are allowed to drink.
        /// </summary>
        internal static string AgeAllowed {
            get {
                return ResourceManager.GetString("AgeAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you 18+ years old?.
        /// </summary>
        internal static string AgeCheck {
            get {
                return ResourceManager.GetString("AgeCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be +18 years old to proceed.
        /// </summary>
        internal static string AgeDenied {
            get {
                return ResourceManager.GetString("AgeDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] - {1} drink list.
        /// </summary>
        internal static string BarStringFormat {
            get {
                return ResourceManager.GetString("BarStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string BarTableAddress {
            get {
                return ResourceManager.GetString("BarTableAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total_average.
        /// </summary>
        internal static string BarTableAverage {
            get {
                return ResourceManager.GetString("BarTableAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map_coordinates.
        /// </summary>
        internal static string BarTableCoordinates {
            get {
                return ResourceManager.GetString("BarTableCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total_count.
        /// </summary>
        internal static string BarTableCount {
            get {
                return ResourceManager.GetString("BarTableCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string BarTableID {
            get {
                return ResourceManager.GetString("BarTableID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string BarTableName {
            get {
                return ResourceManager.GetString("BarTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin\t-871874097\t1.
        /// </summary>
        internal static string BaseAdminValues {
            get {
                return ResourceManager.GetString("BaseAdminValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill all the fields.
        /// </summary>
        internal static string EmptyFields {
            get {
                return ResourceManager.GetString("EmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is nothing to remove.
        /// </summary>
        internal static string EmptyList {
            get {
                return ResourceManager.GetString("EmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar_Data.txt.
        /// </summary>
        internal static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by average.
        /// </summary>
        internal static string FilterConditionAvg {
            get {
                return ResourceManager.GetString("FilterConditionAvg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by percentage.
        /// </summary>
        internal static string FilterConditionPerc {
            get {
                return ResourceManager.GetString("FilterConditionPerc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[0-9]+$.
        /// </summary>
        internal static string FilterNumberReg {
            get {
                return ResourceManager.GetString("FilterNumberReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid minimum value..
        /// </summary>
        internal static string InvalidMinValue {
            get {
                return ResourceManager.GetString("InvalidMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of bars.
        /// </summary>
        internal static string LabelValueBars {
            get {
                return ResourceManager.GetString("LabelValueBars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum value.
        /// </summary>
        internal static string LabelValueMin {
            get {
                return ResourceManager.GetString("LabelValueMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Bar.
        /// </summary>
        internal static string LabelValueNewBar {
            get {
                return ResourceManager.GetString("LabelValueNewBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete?.
        /// </summary>
        internal static string MessegeDelete {
            get {
                return ResourceManager.GetString("MessegeDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the minimal level for filter.
        /// </summary>
        internal static string MinimalFilter {
            get {
                return ResourceManager.GetString("MinimalFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered non-numeric characters.
        /// </summary>
        internal static string NonNumeric {
            get {
                return ResourceManager.GetString("NonNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to show.
        /// </summary>
        internal static string NothingToShow {
            get {
                return ResourceManager.GetString("NothingToShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must match.
        /// </summary>
        internal static string PasswordsDontMatch {
            get {
                return ResourceManager.GetString("PasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The returned list is empty. Try again with different criteria or list.
        /// </summary>
        internal static string ReturnEmpty {
            get {
                return ResourceManager.GetString("ReturnEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User created successfully.
        /// </summary>
        internal static string UserCreated {
            get {
                return ResourceManager.GetString("UserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserData.txt.
        /// </summary>
        internal static string UserDataFile {
            get {
                return ResourceManager.GetString("UserDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This username already exists.
        /// </summary>
        internal static string UsernameTaken {
            get {
                return ResourceManager.GetString("UsernameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong username and/or password.
        /// </summary>
        internal static string WrongLoginData {
            get {
                return ResourceManager.GetString("WrongLoginData", resourceCulture);
            }
        }
    }
}
