//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace holy_water
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drink
    {
        public long Id { get; set; }
        public int Bar_Id { get; set; }
        public System.DateTime Date_time { get; set; }
        public decimal Glass_volume { get; set; }
        public decimal Fill_percentage { get; set; }
    
        public virtual Bar Bar { get; set; }
    }
}
